# see: https://autowarefoundation.github.io/autoware-documentation/main/how-to-guides/integrating-autoware/creating-vehicle-and-sensor-model/creating-vehicle-model/
/**:
  ros__parameters:
    wheel_radius: 0.127 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.1397 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 1.0414 # between front wheel center and rear wheel center
    wheel_tread: 1.27 # between left wheel center and right wheel center
    front_overhang: 0.5461 # between front wheel center and vehicle front
    rear_overhang: 0.4191 # between rear wheel center and vehicle rear
    left_overhang: 0.1397 # between left wheel center and vehicle left
    right_overhang: 0.1397 # between right wheel center and vehicle right
    vehicle_height: 0.508
    max_steer_angle: 0.516 # [rad]