/**:
  ros__parameters:
    default:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: cockpit_teleop
      axis_mappings:
        drive-speed:
          axis: 0
          scale: 0.0
          offset: 0.0
        drive-steering_angle:
          axis: 1
          scale: 0.0
          offset: 0.0

    human_control:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: cockpit_teleop
      deadman_buttons: [9]
      axis_mappings:
        drive-speed:
          axis: 0
          scale: 5.0
          offset: 0.0
        drive-steering_angle:
          axis: 1
          scale: 0.34
          offset: 0.0

    autonomous_control:
      type: topic
      interface_type: std_msgs/msg/Int8
      topic_name: /dev/null
      deadman_buttons: [8]
      message_value:
        data:
          value: 0