# Input topics handled/muxed.
# For each topic:
# - name    : name identifier to select the topic (*sub-namespace, see below)
# - topic   : input topic of ackermann_msgs::AckermannDriveStamped type
# - timeout : timeout in seconds to start discarding old messages, and use 0.0 speed instead
# - priority: priority in the range [0, 255]; the higher the more priority over other topics

ackermann_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : drive
        timeout : 0.2
        priority: 10
      joystick:
        topic   : teleop
        timeout : 0.2
        priority: 200  # 100
      at9s_joystick:
        topic: teleop_at9s
        timeout: 1.0
        priority: 100
      cockpit_joystick:
        topic: teleop_cockpit
        timeout: 0.2
        priority: 50